config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end
  
  resources :reviews, only: [] do
    resources :helpfuls, only: [:create, :destroy]
  end
  
  get '/users/show/:id', to: 'users#show', as: :user
  devise_for :users
  get 'search' => 'searches#index', as: :search
  
  
  root 'rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/helpful.rb
class Helpful < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :room
  has_attached_file :file,
    styles: { medium: '400x300', small: '300x180' },
    default_url: 'missing_:style.jpg'
  validates_attachment :file, presence: true,
    content_type: { content_type: ['image/jpeg', 'image/png', 'image/gif'] },
    size: { in: 0..4.megabytes }

  process_in_background :file
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :room, counter_cache: true
  belongs_to :user
  has_many :helpfuls
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :images, dependent: :destroy, inverse_of: :room
  accepts_nested_attributes_for :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include Gravtastic
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:guest, :host]
  has_many :rooms
  has_gravatar
  has_many :reviews
  has_many :helpfuls
  
  def helpful_for(review)
    helpfuls.where(review_id: review.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end


end

app/controllers/helpfuls_controller.rb
class HelpfulsController < ApplicationController
   def create
        review = Review.find(params[:review_id])
        room = Room.find(review.room_id)
        helpful = current_user.helpfuls.build(review: review)
      
        if helpful.save
            flash[:notice] = "Saved."
        else
            flash[:alert] = "Something's wrong."
        end
        
        redirect_to room
   end
   
   def destroy
        review = Review.find(params[:review_id])
        room = Room.find(review.room_id)
        helpful = current_user.helpfuls.find_by(review_id: params[:review_id])
        if helpful.destroy
            flash[:notice] = "Saved."
        else
            flash[:alert] = "Something's wrong."
        end
        
        redirect_to room
   end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
        @room = Room.find(params[:room_id])
        review = @room.reviews.new(review_params)
        review.user = current_user
        if review.save
            flash[:notice] = "Your review have been saved"
            redirect_to @room
        else
            flash[:alert] = "There's an error, please try again"
            render @room
        end
    end
    
    def destroy
        @room = Room.find(params[:room_id])
        review = @room.reviews.find(params[:id])
        
        if review.destroy
            flash[:notice] = "Review have been deleted"
            redirect_to @room
        else
            flash[:alert] = "Comment couldn't be deleted. Try again."
            redirect_to @room
        end
    end
    
     private
    
    def review_params
        params.require(:review).permit(:body)
    end
    
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.includes(:user, :reviews).find(params[:id])
    @new_review = Review.new
  end

  def new
    if check_role
      @room = Room.new
      @room.images.build
    else
      flash[:alert] = "You are not a host"
      redirect_to root_path
    end
  end

  def create
    if check_role
      @room = current_user.rooms.build(room_params)
      if @room.save
        redirect_to @room, notice: 'Room saved'
      else
        flash[:alert] = 'There was an error, please try again'
        render :new
      end
    else
      flash[:alert] = "You are not a host"
      redirect_to root_path
    end
  end

  def edit
    @room = Room.find(params[:id])
    render root_path unless check_owner(@room)
  end

  def update
    @room = Room.find(params[:id])
    if check_owner(@room)
      if @room.update(room_params)
        flash[:notice] = "The room was updated"
        redirect_to @room, notice: 'Room saved'
      else
        flash[:alert] = 'There was an error, please try again'
        render :edit
      end
    else
      flash[:alert] = "You didn't own this room"
      redirect_to @room
    end
  end

  def destroy
    @room = Room.find(params[:id])
    if check_owner(@room)
      if @room.destroy
        flash[:notice] = "The room was deleted"
        redirect_to root_path
      else
        flash[:alert] = "Something's worng, please try again."
        render :show
      end
    else
      flash[:alert] = "You can't delete other user's room."
      redirect_to @room
    end
  end

  private
  def room_params
    params.require(:room).permit(:title, :description, :city, :country, :latitude, :longitude,
      images_attributes: [:file])
  end

  def check_role
    if current_user.role == 'host'
      true
    else
      false
    end
  end

  def check_owner(room)
    if room.user_id == current_user.id
      true
    else
      false
    end
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def index
        query_param = "%#{params[:keyword]}%"
        if found = Room.where('lower(title) LIKE ?', query_param).first || User.find_by(email: params[:keyword])
            redirect_to found
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def find_user(id)
        User.find(id)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
    
    def count_imgs(room)
        Image.where(room_id: room.id).length
    end
    
    def file_url(x)
        @room.images[x].file.url(:medium)
    end
    
    def file_name(x)
        @room.images[x].file.instance.file_file_name
    end
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airbnc</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&libraries=places"></script>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/geocomplete/1.7.0/jquery.geocomplete.min.js' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery.googlemap/1.5/jquery.googlemap.min.js' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css">
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="row">
        <div class='col-md-4'>
          <%= link_to image_tag("http://placehold.it/70x70?text=A"), root_path, id: "logo" %>
        </div>
        <nav>
          <div class='col-md-8'>
            <ul class="nav navbar-nav navbar-right">
              <li class='search_box_span'>
                <span>
                  <i class='icon-magnifier'></i>
                  <%= form_tag search_path, method: :get, class: 'search_box' do %>
                    <%= text_field_tag 'keyword', nil %>
                  <% end %>
                </span>
              </li>
              <li><%= link_to "Help",   '#' %></li>
              <li><%= link_to 'Become a Host', '#' %></li>
              <% if user_signed_in? %>
                <li><%= link_to user_path(current_user) do %>
                  <%= image_tag current_user.gravatar_url, id: 'userimg' %>
                  <% end %>
                </li>
                <li><%= link_to current_user.first_name, edit_user_registration_path %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Log in", new_user_session_path %></li>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </div>
  </header>
   <% flash.each do |key, value| %>
     <div class="alert alert-<%=key %>"><%=value%></div>
   <% end %>

  <div class="container">
    <main>
      <%= yield %>
    </main>
  </div>
</body>
</html>

app/views/members/show.html.erb
<div class='col-md-12'>
    <div class='col-md-3'>
        <%= image_tag current_user.gravatar_url(:size => 220), class: 'user_profile' %>
        <div class='verified-info'>
            <p class='verified-infop'>Verified info</p>
            <p>Government ID</p>
            <i class='icon-check'></i>
            <p>Personal info</p>
            <i class='icon-check'></i>
            <p>Email address</p>
            <i class='icon-check'></i>
            <p>Phone number</p>
            <i class='icon-check'></i>
            <p><%= link_to 'Learn more >>', '#' %></p>
        </div>
        <div class='about'>
            <p class='aboutp'>About me</p>
            <p>Languages</p>
        </div>
    </div>
    <div class='col-md-9'>
        <h2>Hey, I'm <%= @user.first_name.upcase %>!</h2>
        <h3>location · Joined in <%= @user.created_at.strftime("%B %Y") %> </h3>
        <p class="icon-note report"> Report this user</p>
        <p>Introduction</p>
        <div class='col-md-3 superhost'><img src="http://www.digitalcare.org/wp-content/uploads/2016/04/superhost.png" alt="Superhost img" height="50" weight="50">Superhost</div>
        <div class='col-md-2 reviews'><p>Review</p></div>
        <div class='col-md-2 reviews'><p>References</p></div>
        <div class='col-md-3 verified'><img src="https://static1.squarespace.com/static/55957799e4b0892edbf385bf/t/55f9d587e4b0f1d98227b742/1442515864422/" alt="Superhost img" height="50" weight="50">Verified</div>
    </div>
    <div class='col-md-9'>
        <h2>Wish Lists</h2>
        <div></div>
    </div>
    <div class='col-md-9'>
        <h2>Reviews</h2>
        <h4>Reviews From Guests</h4>
        <div></div>
    </div>
    
</div>

app/views/reviews/_review.html.erb
<%= content_tag :div, class: 'media', id: "reviews-#{review.room.id}" do %>
    <div class='col-md-12'>
        <div class='col-md-2'>
            <%= image_tag find_user(review.user_id).gravatar_url, id: 'review_ownerimg'  %>
        </div>
        <div class='col-md-10'>
            <h4><%= find_user(review.user_id).first_name %></h4>
            <h4 class='review_show_created_at'><%= review.created_at.strftime('%B %Y') %></h4>
        </div>
    </div>
    
    <div class='col-md-12'>
        <%= review.body %>
    </div>
    <div class='col-md-12'>
        <%= link_to "Delete Review", [review.room, review], method: :delete, class: 'btn btn-danger delete_review' %>
        <% if helpful = find_user(current_user.id).helpful_for(review) %>
            <%= link_to review_helpful_path(review), class:'btn btn-default unhelpful_btn', method: :delete do %>
                <i class='icon-dislike'></i>&nbsp; Unhelpful
            <% end %>
        <% else %>
            <%= link_to review_helpfuls_path(review), class:'btn btn-default helpful_btn', method: :post do %>
                <i class='icon-like'></i>&nbsp; Helpful
            <% end %>
        <% end %>
        <div class='btn btn-default report_btn'>
            <i class='icon-flag'></i>
            <span>Report</span>
        </div>
    </div>
<% end %>

app/views/rooms/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= bootstrap_form_for(@room, html: { multipart: true }) do |f| %>
    <%= f.text_field :title %>
    <%= f.text_field :description %>

    <div id="images">
      <%= f.fields_for :images do |image| %>
        <%= render 'image_fields', f: image %>
      <% end %>

      <div class="links">
        <%= link_to_add_association 'add image', f, :images %>
      </div>
    </div>

    <div class="geocomplete">
      <%= label_tag :user_location, 'Enter your city' %>
      <br>
      <%= text_field_tag :user_location %>

      <%= f.hidden_field :latitude, data: { geo: 'lat' } %>
      <%= f.hidden_field :longitude, data: { geo: 'lng' } %>
      <%= f.text_field :city, data: { geo: 'locality' } %>
      <%= f.text_field :country, data: { geo: 'country' } %>

      <div id="geocomplete-map"></div>
    </div>

    <%= f.submit class: 'room_form_submit_btn' %>

    <% end %>

  </div>
</div>


<!-- load map on edit view -->
<script>
  $(document).on('turbolinks:load', function() {
    <% if @room.latitude %>
      $('#geocomplete-map').googleMap({
        zoom: 10,
        coords: [<%= @room.latitude %>, <%= @room.longitude %>]
      });
    <% end %>
  })
</script>

app/views/rooms/_image_fields.html.erb
<div class='nested-fields'>
  <%= f.label :image %>
  <%= f.file_field :file %>
</div>

app/views/rooms/edit.html.erb
<h1 class='room_edit_view_title'>edit room <%= @room.id %></h1>
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class='row'>
    <div class='col-md-8'>
        <% @rooms.each_with_index do |room, index| %>
            <div class='col-md-6 room_index_page'>
                <div class='room'>
                    <p>price - favorite tag</p>
                    <%= link_to room do %>
                        <div id='carousel-example-generic-<%= index %>' class='carousel slide' data-ride="carousel">
                            <div class='carousel-inner room_index_page' role='listbox'>
                                <% room.images.each_with_index do |img, idx| %>
                                    <div class="item <%= 'active' if idx == 0 %>">
                                      <%= image_tag(img.file.url(:medium), alt: img.file.instance.file_file_name) %>
                                    </div>
                                <% end %>
                            </div>
                            <a class='left carousel-control' href='#carousel-example-generic-<%= index %>' role='button' data-slide='prev'>
                                <span class='glyphicon glyphicon-chevron-left' aria-hidden='true'></span>
                                <span class='sr-only'>Previous</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic-<%= index %>" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    <% end %>    
                    <h1 class='roomname'><%= room.title %></h1>
                    <p>Private - 1 guest - <%= pluralize(room.reviews_count, 'views') %> - <%= image_tag find_user(room.user_id).gravatar_url, id: 'room_index_userimg' %></p>
                </div>
            </div>
        <% end %>
    </div>
    <div class="col-md-4">
        <% if current_user.host? %>
            <%= link_to 'Add room', new_room_path, class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/rooms/new.html.erb
<h1>Add new room</h1>
<%= render 'form' %>

app/views/rooms/show.html.erb
<div id='carousel-example-generic' class='carousel slide' data-ride="carousel">
    <ol class='carousel-indicators'>
        <% @room.images.each_with_index do |img, idx| %>
           <li data-target='#carousel-example-generic' data-slide-to=<%= idx %> class=<%= 'active' if idx == 0 %>></li>
        <% end %>
    </ol>
    <div class='carousel-inner' role='listbox'>
        <% @room.images.each_with_index do |img, idx| %>
            <div class="item <%= 'active' if idx == 0 %>">
              <%= image_tag(img.file.url(:medium), alt: img.file.instance.file_file_name) %>
            </div>
        <% end %>
    </div>
    <a class='left carousel-control' href='#carousel-example-generic' role='button' data-slide='prev'>
        <span class='glyphicon glyphicon-chevron-left' aria-hidden='true'></span>
        <span class='sr-only'>Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class='col-md-8 show_room_info'>
    <div class='col-md-10'>
        <h1><%= @room.title %></h1>
        <p><%= @room.city %>, <%= @room.country %> - <%= pluralize(@room.reviews_count,'review') %></p>
    </div>
    <div class='col-md-2 room_ownerimg'>
        <%= image_tag @room.user.gravatar_url, id: 'room_ownerimg' %>
    </div>
    <div class='col-md-12'>
        <p>Private - guest# - bed#</p>
    </div>
    <div class='col-md-12'>
        <p>Room detail</p>
    </div>
    <div class='col-md-12'>
        <p><%= @room.description %></p>
    </div>
    <div class='col-md-12'>
        <h2>Reviews</h2>
        <%= form_for [@room, @new_review] do |f| %>
            <div class="form-group">
                <%= f.label :body, class: 'sr-only' %>
                <%= f.text_field :body, class: 'form-control', placeholder: "Enter a new review" %>
            </div>
            <%= f.submit "Submit Review", class: 'btn btn-default pull-right' %>
        <% end %>
        <div class='col-md-12 review'>
            <%= render @room.reviews %>
        </div>
    </div>

</div>
<div class='col-md-4 room_show_price'>
    <% if @room.user_id == current_user.id %>
        <%= link_to "Update info", edit_room_path(@room), class: 'btn btn-info' %>
        <%= link_to "Delete room", @room ,method: :delete , class: 'btn btn-danger' %>
    <%end %>
    <h1>price</h1>
    <p>favorite</p>
</div>

app/views/searches/index.html.erb
Search view

app/views/users/show.html.erb
<div class='col-md-12'>
    <div class='col-md-3'>
        <%= image_tag current_user.gravatar_url(:size => 220), class: 'user_profile' %>
        <div class='verified-info'>
            <p class='verified-infop'>Verified info</p>
            <p>Government ID</p>
            <i class='icon-check'></i>
            <p>Personal info</p>
            <i class='icon-check'></i>
            <p>Email address</p>
            <i class='icon-check'></i>
            <p>Phone number</p>
            <i class='icon-check'></i>
            <p><%= link_to 'Learn more >>', '#' %></p>
        </div>
        <div class='about'>
            <p class='aboutp'>About me</p>
            <p>Languages</p>
        </div>
    </div>
    <div class='col-md-9'>
        <h2>Hey, I'm <%= @user.first_name.upcase %>!</h2>
        <h3>location · Joined in <%= @user.created_at.strftime("%B %Y") %> </h3>
        <p class="icon-note report"> Report this user</p>
        <p>Introduction</p>
        <div class='col-md-3 superhost'><img src="http://www.digitalcare.org/wp-content/uploads/2016/04/superhost.png" alt="Superhost img" height="50" weight="50">Superhost</div>
        <div class='col-md-2 reviews'><p>Review</p></div>
        <div class='col-md-2 reviews'><p>References</p></div>
        <div class='col-md-3 verified'><img src="https://static1.squarespace.com/static/55957799e4b0892edbf385bf/t/55f9d587e4b0f1d98227b742/1442515864422/" alt="Superhost img" height="50" weight="50">Verified</div>
    </div>
    <div class='col-md-9'>
        <h2>Wish Lists</h2>
        <div></div>
    </div>
    <div class='col-md-9'>
        <h2>Reviews</h2>
        <h4>Reviews From Guests</h4>
        <div></div>
    </div>

</div>